apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: email-distribution
  labels:
    app.kubernetes.io/name: email-distribution
    app.kubernetes.io/component: config
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  AWS_REGION: "us-east-1"
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30s"
  SQS_POLLING_INTERVAL: "5s"
  MAX_CONCURRENT_CUSTOMERS: "20"
  RETRY_MAX_ATTEMPTS: "3"
  CIRCUIT_BREAKER_THRESHOLD: "5"
  CIRCUIT_BREAKER_TIMEOUT: "30s"
  DEAD_LETTER_QUEUE_ENABLED: "true"
  MONITORING_NAMESPACE: "EmailDistribution"
  ALERT_MANAGER_URL: "http://alertmanager:9093"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
  namespace: email-distribution
  labels:
    app.kubernetes.io/name: email-distribution
    app.kubernetes.io/component: config
data:
  customers.json: |
    {
      "customerMappings": {
        "hts": {
          "customerName": "HTS Production",
          "awsAccountId": "123456789012",
          "region": "us-east-1",
          "sesRoleArn": "arn:aws:iam::123456789012:role/HTSSESRole",
          "sqsRoleArn": "arn:aws:iam::123456789012:role/HTSSQSRole",
          "s3RoleArn": "arn:aws:iam::123456789012:role/HTSS3Role",
          "environment": "production"
        },
        "cds": {
          "customerName": "CDS Global",
          "awsAccountId": "234567890123",
          "region": "us-west-2",
          "sesRoleArn": "arn:aws:iam::234567890123:role/CDSSESRole",
          "sqsRoleArn": "arn:aws:iam::234567890123:role/CDSSQSRole",
          "environment": "production"
        }
      }
    }